import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const garfield: Town = {
  id: 'nj-bergen-garfield',
  name: 'Garfield',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z14013)
    {
      id: 'garfield-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday & Thursday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 4], // Monday, Thursday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Garfield Shred and Recycling Day',
          oddLabel: 'Garfield Shred and Recycling Day',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z14014)
    {
      id: 'garfield-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Garfield Shred and Recycling Day',
          oddLabel: 'Garfield Shred and Recycling Day',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z14015)
    {
      id: 'garfield-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected Wednesday & Saturday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [3, 6], // Wednesday, Saturday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Garfield Shred and Recycling Day',
          oddLabel: 'Garfield Shred and Recycling Day',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z14016)
    {
      id: 'garfield-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Paper',
          oddLabel: 'Commingled',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 5 (RecycleCoach zone: zone-z14017)
    {
      id: 'garfield-zone-5',
      name: 'Zone 5',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 2, // Tuesday
          weeks: {
            even: 'commingled',
            odd: 'paper',
          },
          evenLabel: 'Commingled',
          oddLabel: 'Paper',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 6 (RecycleCoach zone: zone-z14018)
    {
      id: 'garfield-zone-6',
      name: 'Zone 6',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'commingled',
            odd: 'paper',
          },
          evenLabel: 'Commingled',
          oddLabel: 'Paper',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 7 (RecycleCoach zone: zone-z14019)
    {
      id: 'garfield-zone-7',
      name: 'Zone 7',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'commingled',
            odd: 'paper',
          },
          evenLabel: 'Commingled',
          oddLabel: 'Paper',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 8 (RecycleCoach zone: zone-z14020)
    {
      id: 'garfield-zone-8',
      name: 'Zone 8',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 5, // Friday
          weeks: {
            even: 'commingled',
            odd: 'paper',
          },
          evenLabel: 'Commingled',
          oddLabel: 'Paper',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Garfield Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
