import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const lyndhurst: Town = {
  id: 'nj-bergen-lyndhurst',
  name: 'Lyndhurst',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13792)
    {
      id: 'lyndhurst-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13794)
    {
      id: 'lyndhurst-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Wednesday & Saturday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [3, 6], // Wednesday, Saturday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z13795)
    {
      id: 'lyndhurst-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected Tuesday & Thursday & Saturday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 4, 6], // Tuesday, Thursday, Saturday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z13796)
    {
      id: 'lyndhurst-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 5 (RecycleCoach zone: zone-z13799)
    {
      id: 'lyndhurst-zone-5',
      name: 'Zone 5',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 6 (RecycleCoach zone: zone-z13800)
    {
      id: 'lyndhurst-zone-6',
      name: 'Zone 6',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 5, // Friday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Lyndhurst Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
