import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const montvale: Town = {
  id: 'nj-bergen-montvale',
  name: 'Montvale',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13771)
    {
      id: 'montvale-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1], // Monday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13772)
    {
      id: 'montvale-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Tuesday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2], // Tuesday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z13773)
    {
      id: 'montvale-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected Wednesday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [3], // Wednesday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z13774)
    {
      id: 'montvale-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'none',
            odd: 'commingled',
          },
          evenLabel: 'No pickup',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 5 (RecycleCoach zone: zone-z13775)
    {
      id: 'montvale-zone-5',
      name: 'Zone 5',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'none',
            odd: 'commingled',
          },
          evenLabel: 'No pickup',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 6 (RecycleCoach zone: zone-z13776)
    {
      id: 'montvale-zone-6',
      name: 'Zone 6',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycling',
          oddLabel: 'No pickup',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 7 (RecycleCoach zone: zone-z13777)
    {
      id: 'montvale-zone-7',
      name: 'Zone 7',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycling',
          oddLabel: 'No pickup',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Montvale Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
