import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const bergenfield: Town = {
  id: 'nj-bergen-bergenfield',
  name: 'Bergenfield',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13157)
    {
      id: 'bergenfield-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday & Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 2, 5], // Monday, Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13158)
    {
      id: 'bergenfield-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Monday & Tuesday & Thursday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 2, 4], // Monday, Tuesday, Thursday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 2, // Tuesday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z13159)
    {
      id: 'bergenfield-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected Tuesday & Thursday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 4, 5], // Tuesday, Thursday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z13160)
    {
      id: 'bergenfield-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected Monday & Thursday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 4, 5], // Monday, Thursday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 5, // Friday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Bergenfield Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
