import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const cresskill: Town = {
  id: 'nj-bergen-cresskill',
  name: 'Cresskill',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13242)
    {
      id: 'cresskill-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'commingled',
            odd: 'paper',
          },
          evenLabel: 'Commingled',
          oddLabel: 'Paper',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13243)
    {
      id: 'cresskill-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 4, // Thursday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Paper',
          oddLabel: 'Commingled',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Cresskill Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
