import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const edgewater: Town = {
  id: 'nj-bergen-edgewater',
  name: 'Edgewater',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13429)
    {
      id: 'edgewater-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday & Wednesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 3, 5], // Monday, Wednesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Cardboard',
          oddLabel: 'Commingled',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13430)
    {
      id: 'edgewater-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Monday & Wednesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 3, 5], // Monday, Wednesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Cardboard',
          oddLabel: 'Commingled',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Edgewater Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
