import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const franklinLakes: Town = {
  id: 'nj-bergen-franklin-lakes',
  name: 'Franklin Lakes',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z13852)
    {
      id: 'franklinLakes-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday & Thursday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 4], // Monday, Thursday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Paper',
          oddLabel: 'Commingled',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '04-01',
          seasonEnd: '09-30',
        },
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z13853)
    {
      id: 'franklinLakes-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'paper',
            odd: 'commingled',
          },
          evenLabel: 'Paper',
          oddLabel: 'Commingled',
        },
        yardWaste: {
          days: [2], // Tuesday
          seasonStart: '04-01',
          seasonEnd: '09-30',
        },
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Franklin Lakes Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
