import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const hoHoKus: Town = {
  id: 'nj-bergen-ho-ho-kus',
  name: 'Ho-Ho-Kus',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z12905)
    {
      id: 'hoHoKus-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected Monday & Thursday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 4], // Monday, Thursday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z12906)
    {
      id: 'hoHoKus-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'commingled',
            odd: 'commingled',
          },
          evenLabel: 'Recycling',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z12907)
    {
      id: 'hoHoKus-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z12908)
    {
      id: 'hoHoKus-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        yardWaste: {
          days: [3], // Wednesday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 5 (RecycleCoach zone: zone-z12909)
    {
      id: 'hoHoKus-zone-5',
      name: 'Zone 5',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        yardWaste: {
          days: [4], // Thursday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 6 (RecycleCoach zone: zone-z12910)
    {
      id: 'hoHoKus-zone-6',
      name: 'Zone 6',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        // TODO: Recycling schedule not detected — verify manually
        recycling: {
          type: 'alternating',
          day: 0, // TODO: day unknown
          weeks: { even: 'commingled', odd: 'paper' },
          evenLabel: 'Commingled Recycling',
          oddLabel: 'Paper Recycling',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '11-01',
          seasonEnd: '12-30',
        },
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Ho-Ho-Kus Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
