import { Town } from '@/data/types';

// Source: RecycleCoach API (recyclecoach.com)
// Scraped: 2026-03-25 — auto-generated by scripts/scrape-recyclecoach.ts
//
// TODOs before this file is production-ready:
//   1. Verify schedule accuracy against the municipal website
//   2. Add recyclingCenter (address, hours, phone)
//   3. Add specialInstructions from the DPW page
//   4. Add street-to-zone assignments if the town has multiple zones
//   5. Check yard waste season dates

export const mahwah: Town = {
  id: 'nj-bergen-mahwah',
  name: 'Mahwah',
  state: 'NJ',
  county: 'Bergen',

  zones: [
    // Zone 1 (RecycleCoach zone: zone-z14042)
    {
      id: 'mahwah-zone-1',
      name: 'Zone 1',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 1, // Monday
          weeks: {
            even: 'none',
            odd: 'commingled',
          },
          evenLabel: 'No pickup',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 2 (RecycleCoach zone: zone-z14043)
    {
      id: 'mahwah-zone-2',
      name: 'Zone 2',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 2, // Tuesday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycling',
          oddLabel: 'No pickup',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 3 (RecycleCoach zone: zone-z14044)
    {
      id: 'mahwah-zone-3',
      name: 'Zone 3',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycling',
          oddLabel: 'No pickup',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 4 (RecycleCoach zone: zone-z14046)
    {
      id: 'mahwah-zone-4',
      name: 'Zone 4',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 2, // Tuesday
          weeks: {
            even: 'none',
            odd: 'commingled',
          },
          evenLabel: 'No pickup',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 5 (RecycleCoach zone: zone-z14047)
    {
      id: 'mahwah-zone-5',
      name: 'Zone 5',
      description: 'Garbage collected TODO: verify',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [], // TODO
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 3, // Wednesday
          weeks: {
            even: 'none',
            odd: 'commingled',
          },
          evenLabel: 'No pickup',
          oddLabel: 'Recycling',
        },
        // yardWaste: { days: [], seasonStart: 'MM-DD', seasonEnd: 'MM-DD' }, // TODO: verify
      },
    },

    // Zone 6 (RecycleCoach zone: zone-z14048)
    {
      id: 'mahwah-zone-6',
      name: 'Zone 6',
      description: 'Garbage collected Monday & Thursday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [1, 4], // Monday, Thursday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycle Yard Closure',
          oddLabel: 'No pickup',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '10-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 7 (RecycleCoach zone: zone-z14049)
    {
      id: 'mahwah-zone-7',
      name: 'Zone 7',
      description: 'Garbage collected Tuesday & Friday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [2, 5], // Tuesday, Friday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycle Yard Closure',
          oddLabel: 'No pickup',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '10-01',
          seasonEnd: '12-30',
        },
      },
    },

    // Zone 8 (RecycleCoach zone: zone-z14050)
    {
      id: 'mahwah-zone-8',
      name: 'Zone 8',
      description: 'Garbage collected Wednesday & Saturday',
      streets: [], // TODO: Street assignments not available via RecycleCoach
      schedule: {
        garbage: {
          days: [3, 6], // Wednesday, Saturday
          time: '6:00 AM', // TODO: verify curb-out time
        },
        recycling: {
          type: 'alternating',
          day: 6, // Saturday
          weeks: {
            even: 'commingled',
            odd: 'none',
          },
          evenLabel: 'Recycle Yard Closure',
          oddLabel: 'No pickup',
        },
        yardWaste: {
          days: [1], // Monday
          seasonStart: '10-01',
          seasonEnd: '12-30',
        },
      },
    }
  ],

  // recyclingCenter: {
  //   name: 'Mahwah Recycling Center',
  //   address: 'TODO',
  //   hours: { weekday: 'TODO', saturday: 'TODO' },
  //   phone: 'TODO',
  // },

  // specialInstructions: [],
};
